### ISSUE TITLE
Add Poppins Project capabilities

### ISSUE THREAD

**Issue by tiagostutz** [tiagostutz/demo-warehouse-software#25]
Make this a Poppins project!

See: https://github.com/bancodobrasil/poppins

**Comment by Geraldlyon** [comment]
Hi I would love to contribute

**Comment by tiagostutz** [comment]
Hi @Geraldlyon ! Welcome onboard.!
So, basically, you will Fork this repo, follow the instructions on the Poppins manifesto to update the README of this project and then open a Pull Request.
Is it ok?

**Comment by nishitpatel1292** [comment]
Hi @tiagostutz! 
Can i contribute now?

**Comment by tiagostutz** [comment]
> Hi @tiagostutz!
> Can i contribute now?

Absolutely.!
Go ahead

**Comment by MayankBansal12** [comment]
Hi @tiagostutz 
I have read the manifesto in the Poppins repo. To make it a Poppins project, we need to add the Poppins badge and specific content in the readme. Do let me know if I can go ahead with the changes.

**Comment by tiagostutz** [comment]
Yes, please. Go ahead!

**Comment by MayankBansal12** [comment]
Done. Please check PR #27 and let me know.
