### ISSUE TITLE
Implement `/health` for Article and Product endpoints

### ISSUE THREAD

**Issue by tiagostutz** [tiagostutz/demo-warehouse-software#8]
Implement a /health that makes a simple query on the database to check whether the service is OK.
Returns:
* 204: OK - query runs successfully in less than 100ms.
* 404: Degraded - if some issue happen in this database simple query

**Comment by arvind-1** [comment]
@tiagostutz Can i work on this issue?

**Comment by tiagostutz** [comment]
Sure! Just assigned to you.!

**Comment by arvind-1** [comment]
@tiagostutz i was trying to setup code locally but i am unable to fetch any data from database locally just an empty list. Could you please help on that.

**Comment by nabanitadewan** [comment]
@tiagostutz Hi! If this is still open , can I work on this?

**Comment by tiagostutz** [comment]
Yep, this is.!
Go ageah, assigning the issue to you.
Nice 🤠
